# frozen_string_literal: true

FactoryBot.define do
  factory :account_membership do
    association :user
    association :account
    role { :owner }
    status { :active }
    # public_id is auto-generated by database via gen_uuidv7()
  end
end
