# frozen_string_literal: true

FactoryBot.define do
  factory :account do
    name { Faker::Company.name }
    status { :active }
    plan { :free }
    # public_id is auto-generated by database via gen_uuidv7()
  end
end
