# frozen_string_literal: true

FactoryBot.define do
  factory :api_key do
    association :user
    association :account
    name { "Test API Key" }
    prefix { "ak_live_#{SecureRandom.alphanumeric(8)}" }
    secret_digest { BCrypt::Password.create("test_secret", cost: 4) }
    scopes { ["posts:read", "posts:write"] }
    environment { :live }
    expires_at { nil }
    revoked_at { nil }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :test_environment do
      environment { :test }
      prefix { "ak_test_#{SecureRandom.alphanumeric(8)}" }
    end

    trait :revoked do
      revoked_at { 1.hour.ago }
    end

    trait :expired do
      expires_at { 1.day.ago }
    end

    trait :admin do
      scopes { ["admin:*"] }
    end

    trait :read_only do
      scopes { ["posts:read", "blogs:read", "drafts:read"] }
    end

    # Creates an API key with a known secret for testing authentication
    trait :with_known_secret do
      transient do
        raw_secret { "test_secret_12345" }
      end

      secret_digest { BCrypt::Password.create(raw_secret, cost: 4) }
    end
  end
end
