# frozen_string_literal: true

FactoryBot.define do
  factory :blog do
    association :account
    name { Faker::Lorem.words(number: 3).join(" ").titleize }
    sequence(:slug) { |n| "blog-#{n}" }
    description { Faker::Lorem.paragraph }
    settings { {} }
    status { :active }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :archived do
      status { :archived }
    end

    trait :deleted do
      status { :deleted }
    end

    trait :with_posts do
      transient do
        posts_count { 3 }
      end

      after(:create) do |blog, evaluator|
        create_list(:post, evaluator.posts_count, blog: blog, account: blog.account)
      end
    end
  end
end
