# frozen_string_literal: true

FactoryBot.define do
  factory :category do
    association :account
    name { Faker::Lorem.unique.words(number: 2).join(" ").titleize }
    sequence(:slug) { |n| "category-#{n}" }
    description { Faker::Lorem.paragraph }
    position { 0 }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :with_parent do
      parent { association(:category, account: account) }
    end

    trait :with_children do
      transient do
        children_count { 3 }
      end

      after(:create) do |category, evaluator|
        create_list(:category, evaluator.children_count, parent: category, account: category.account)
      end
    end

    trait :with_posts do
      transient do
        posts_count { 3 }
      end

      after(:create) do |category, evaluator|
        create_list(:post, evaluator.posts_count, category: category, account: category.account)
      end
    end
  end
end
