# frozen_string_literal: true

FactoryBot.define do
  factory :draft do
    account { association :account }
    blog { association(:blog, account: account) }
    author { association :user }
    title { Faker::Lorem.sentence(word_count: 4) }
    content { Faker::Lorem.paragraphs(number: 3).join("\n\n") }
    autosaved_at { Time.current }
    metadata { {} }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :linked_to_post do
      association :post
    end

    trait :empty do
      title { nil }
      content { nil }
    end

    trait :with_tags do
      transient do
        tags_count { 2 }
      end

      after(:create) do |draft, evaluator|
        tags = create_list(:tag, evaluator.tags_count, account: draft.account)
        tags.each do |tag|
          create(:tagging, tag: tag, taggable: draft, account: draft.account)
        end
      end
    end
  end
end
