# frozen_string_literal: true

FactoryBot.define do
  factory :post do
    transient do
      create_blog { true }
    end

    account { association :account }
    blog { create_blog ? association(:blog, account: account) : nil }
    author { association :user }
    title { Faker::Lorem.sentence(word_count: 5) }
    sequence(:slug) { |n| "post-#{n}" }
    content { Faker::Lorem.paragraphs(number: 5).join("\n\n") }
    excerpt { Faker::Lorem.paragraph }
    status { :draft }
    featured { false }
    metadata { {} }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :published do
      status { :published }
      published_at { Time.current }
    end

    trait :scheduled do
      status { :scheduled }
      scheduled_for { 1.week.from_now }
    end

    trait :archived do
      status { :archived }
    end

    trait :featured do
      featured { true }
    end

    trait :with_seo do
      seo_title { Faker::Lorem.sentence(word_count: 8) }
      seo_description { Faker::Lorem.paragraph }
    end

    trait :with_category do
      association :category
    end

    trait :with_tags do
      transient do
        tags_count { 3 }
      end

      after(:create) do |post, evaluator|
        tags = create_list(:tag, evaluator.tags_count, account: post.account)
        tags.each do |tag|
          create(:tagging, tag: tag, taggable: post, account: post.account)
        end
      end
    end

    trait :with_revisions do
      transient do
        revisions_count { 2 }
      end

      after(:create) do |post, evaluator|
        create_list(:revision, evaluator.revisions_count, post: post, account: post.account, created_by: post.author)
      end
    end
  end
end
