# frozen_string_literal: true

FactoryBot.define do
  factory :refresh_token do
    association :user
    jti { SecureRandom.uuid }
    token_digest { Digest::SHA256.hexdigest(SecureRandom.urlsafe_base64(32)) }
    expires_at { 30.days.from_now }
    device_info { {} }
    # public_id is auto-generated by database via gen_uuidv7()
  end
end
