# frozen_string_literal: true

FactoryBot.define do
  factory :revision do
    account { association :account }
    post { association(:post, account: account) }
    created_by { association :user }
    title { Faker::Lorem.sentence(word_count: 5) }
    content { Faker::Lorem.paragraphs(number: 4).join("\n\n") }
    sequence(:revision_number) { |n| n }
    metadata { {} }
    # public_id is auto-generated by database via gen_uuidv7()
  end
end
