# frozen_string_literal: true

FactoryBot.define do
  factory :tagging do
    account { association :account }
    tag { association(:tag, account: account) }
    taggable { association(:post, account: account) }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :for_post do
      association :taggable, factory: :post
    end

    trait :for_draft do
      association :taggable, factory: :draft
    end
  end
end
