# frozen_string_literal: true

FactoryBot.define do
  factory :tag do
    association :account
    name { Faker::Lorem.unique.word.downcase }
    sequence(:slug) { |n| "tag-#{n}" }
    color { Faker::Color.hex_color }
    # public_id is auto-generated by database via gen_uuidv7()

    trait :without_color do
      color { nil }
    end

    trait :popular do
      transient do
        posts_count { 5 }
      end

      after(:create) do |tag, evaluator|
        posts = create_list(:post, evaluator.posts_count, account: tag.account)
        posts.each do |post|
          create(:tagging, tag: tag, taggable: post, account: tag.account)
        end
      end
    end
  end
end
