# frozen_string_literal: true

FactoryBot.define do
  factory :user do
    email { Faker::Internet.email }
    password { 'Password123!' }
    name { Faker::Name.name }
    # public_id is auto-generated by database via gen_uuidv7()
  end
end
