AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'config/puma.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/environments/**/*'

require:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/routes.rb'
    - 'config/initializers/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'spec/**/*'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 10
