inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "config/puma.rb"
    - "config/boot.rb"
    - "config/environment.rb"
    - "config/environments/**/*"

plugins:
  - rubocop-rails
  - rubocop-rspec

Layout/LineLength:
  Max: 120
  Exclude:
    - "config/routes.rb"
    - "config/initializers/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"
    - "config/environments/**/*"

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 20
  Exclude:
    - "spec/**/*"

# Disable some overly strict RSpec cops
RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4

RSpec/LetSetup:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for
    - and
    - as

RSpec/ContextMethod:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

# Allow update_column for performance-critical operations
Rails/SkipsModelValidations:
  Enabled: false

# Allow I18n locale texts in controllers for error messages
Rails/I18nLocaleTexts:
  Enabled: false

# Use modern HTTP status names
Rails/HttpStatusNameConsistency:
  Enabled: true

# Allow OpenStruct for simple data objects
Style/OpenStructUse:
  Enabled: false

# Lint cops that are too strict
Lint/MissingSuper:
  Enabled: false

# Allow rescue without specifying error class in specific cases
Style/RescueStandardError:
  Enabled: false
